name: CI/CD Pipeline - GitHub Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Backend
        working-directory: ./TestApiBackend
        run: dotnet build

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Frontend
        working-directory: ./test-frontend
        run: |
          npm install
          npm run build

      - name: Database Check
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          PGPASSWORD=JenkinsCheck123 psql -h 13.206.119.124 -U postgres -c "SELECT 1;"
